name = "gold-price-tracker"
main = "worker.js"
compatibility_date = "2026-08-12"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "markettracker"
database_id = "df12a1b7-a9aa-4989-bee5-f4765d01cfca"

[triggers]
crons = ["*/15 * * * *"]
