name = "gold-price-tracker"
main = "worker.js"
compatibility_date = "2026-08-12"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "gold-price-tracker-db"
database_id = "REPLACE_ME_WITH_D1_DATABASE_ID"

[triggers]
crons = ["*/15 * * * *"]
